// This file is automatically generated by the task build:autogen

import * as _choice from './choice';
import * as _count from './count';
import * as _diereason from './diereason';
import * as _info from './info';
import * as _randomid from './random-id';
import * as _team from './team';
import * as _votebox from './votebox';

export {
    _choice as choice,
    _count as count,
    _diereason as diereason,
    _info as info,
    _randomid as randomid,
    _team as team,
    _votebox as votebox,
};
