// This file is automatically generated by the task build:autogen

import * as _choice from './choice.ts';
import * as _count from './count.ts';
import * as _diereason from './diereason.ts';
import * as _info from './info.ts';
import * as _randomid from './random-id.ts';
import * as _team from './team.ts';
import * as _votebox from './votebox.ts';

export {
    _choice as choice,
    _count as count,
    _diereason as diereason,
    _info as info,
    _randomid as randomid,
    _team as team,
    _votebox as votebox,
};
